---
- name: "Cluster configuration"
  hosts: cluster
  remote_user: ec2-user
  gather_facts: false
  become: yes
  become_method: sudo
  become_user: root
  
  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:

  roles:
    - install-dependencies
