---
- name: "Server configuration"
  hosts: server
  user: ec2-user
  gather_facts: false
  become: yes
  become_method: sudo
  become_user: root
  
  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
      
    - name: "Install 'unzip'"
      apt:
        name: [ "unzip" ]
        state: latest
        update_cache: yes
        
    - name: "install python for Ansible."
      become: true
      apt:
        name: "python3"
        state: "latest"
        update_cache: yes

  roles:
    - install-dependencies
