- name: "Deploy app to EC2 kubernetes cluster"
  hosts: cluster
  remote_user: ec2-user
  gather_facts: false
  vars:
    CIRCLE_WORKFLOW_ID: "{{ lookup('env', 'CIRCLE_WORKFLOW_ID') }}"
  tasks:
    - name: Run docker
      become: yes
      shell: systemctl start docker.service
      args:
        chdir: $HOME
  
    - name: Start kubernetes
      shell: minikube start --driver=docker --force
      args:
        chdir: $HOME
  
    - name: Run the Docker Hub container with kubernetes
      shell: kubectl create deploy capstone-project --image=docker.io/manhnguyen308/capstone-project:latest
      args:
        chdir: $HOME

    - name: Waiting for pod to be ready
      shell: sleep 180
      args:
        chdir: $HOME
    
    - name: Forward the container port to a host
      shell: nohup kubectl port-forward deployment.apps/capstone-project 8000:80 --address='0.0.0.0' &
      args:
        chdir: $HOME