Parameters:
  EnvironmentName:
    Description: An Environment name that will be prefixed to resources
    Default: capstone-project
    Type: String
  SSHKeyName:
    Description: SSH key for cluster access
    Type: String
  amiImageId:
    Description: Image ID for instance
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${EnvironmentName}-cluster-SG
      GroupDescription: Allow port 22 and port 8000
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 0.0.0.0/0

  cluster:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.small
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: !Ref SSHKeyName
      ImageId: !Ref amiImageId
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: '30'
            VolumeType: gp2
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-cluster
        - Key: Project
          Value: !Ref EnvironmentName
